<a href="https://colab.research.google.com/github/beingTushar24/Pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


## Introduction to Tensors

## Creating tensors

In [15]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [16]:
scalar.ndim

0

In [17]:
# Get tensor back as python int
scalar.item()

7

In [18]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [19]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

In [21]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX[1]

tensor([ 9, 10])

In [24]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3 ,6 ,9],
                        [2 ,4 ,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [27]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor

why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those numbers to better represent the data.

In [29]:
## Random Tensor
## creating a random tensor of size 3X4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1828, 0.6362, 0.1431, 0.2649],
        [0.9623, 0.1221, 0.2340, 0.9407],
        [0.2254, 0.8925, 0.7470, 0.6315]])

In [30]:
random_tensor.ndim

2

In [31]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 4]), 2)

In [32]:
torch.rand(size=(3,3))

tensor([[0.3026, 0.5853, 0.0801],
        [0.8829, 0.7221, 0.0243],
        [0.5626, 0.5205, 0.0137]])

In [33]:
torch.rand(3,3)

tensor([[0.0365, 0.6593, 0.3154],
        [0.6002, 0.9866, 0.4085],
        [0.4587, 0.6217, 0.5339]])

### Zeros And Ones

In [34]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros.shape

torch.Size([3, 4])

In [36]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like


In [40]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=0, end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# Creating Tensor Like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

*NOTE :* Tensors datatypes is one of the 3 big errors we'll run into pytorch & deep learning
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on the right device

In [42]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is a tensor(eg. float)
                               device=None,# whar device is your tensor on
                               requires_grad=False) # wheather or not to track gradeints with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor = torch.tensor([3,4,9],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

### Getting information from tensor

1. Tensors not right Datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get a device from a tensor, can use tensor.device



In [48]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3665, 0.9163, 0.5826, 0.9417],
        [0.7887, 0.9346, 0.1969, 0.5544],
        [0.0127, 0.6788, 0.0016, 0.2045]])

In [49]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3665, 0.9163, 0.5826, 0.9417],
        [0.7887, 0.9346, 0.1969, 0.5544],
        [0.0127, 0.6788, 0.0016, 0.2045]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensor (tensor opereation)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [50]:
# Create a Tensor and add 10 to it

tensor = torch.tensor([1,2,3,4])
tensor +10

tensor([11, 12, 13, 14])

In [51]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30, 40])

In [52]:
# Substract -10

tensor - 10

tensor([-9, -8, -7, -6])

In [53]:
# Try out pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30, 40])

## Matrix Multiplication

Two main ways of performing Multiplication in nural network and deep learning

1.Element-wise Multiplication
2.Matrix multiplication(dot product)


In [54]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
Equals: tensor([ 1,  4,  9, 16])


In [55]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(30)

In [56]:
tensor

tensor([1, 2, 3, 4])

In [57]:
%%time
value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(30)
CPU times: user 879 µs, sys: 0 ns, total: 879 µs
Wall time: 3.67 ms


In [58]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 187 µs, sys: 32 µs, total: 219 µs
Wall time: 182 µs


tensor(30)

## one of the most common error in deep learning : shape error

In [59]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape , tensor_B.shape

To fix our tensor shape issue, we can manipulate tensor using a **transpose** switches the axis or dimensions of a given tensor.

In [60]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [61]:
## The matrix Multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## finding the min, max, mean , sum ,etc(Tensor aggregation)

In [62]:
# create a tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [63]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [64]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [65]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [66]:
# find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [67]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [68]:
## find the position in the tensor that has the minimum value with argmin() -> returns index place of the minimum element in the tensor
x.argmin()


tensor(0)

In [69]:
x[0]

tensor(1)

In [70]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [71]:
x[9]

tensor(91)

## Reshaping stacking , squeezing , and unsquessing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory
* stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* seueeze - removes all `1` dimensional from a tensor
* Unsqueeze - add a `1` dimensional to a target tensor
* Permute - return a few input with dimensional pemuted (swapped) in a certain way

In [72]:
# let's create a tensor
x =  torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# changing z changes z (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
# stacking tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
# torch squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_squeeze
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [78]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimenion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [79]:
# torch.permute() - rearranges the dimension of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3)) #[height, width, colour_channel]

# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [80]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [81]:
x_reshaped.shape

torch.Size([1, 9])

In [82]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
x_reshaped.squeeze().shape

torch.Size([9])

## Indexing (selecting data from tensor)

Indexing with pythorch is same as to indexing with Numpy

In [84]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
# let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [87]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [88]:
print(x[0][2][2])

tensor(9)


## Pytorch tensor and Numpy

Numpy is a popular scientific Python numerical library.

And because of this , python has functinalitty to interect with it.
*Data in Numpy, want in pytorch tensor->`torch.from_numpy(ndarray)`
*Pytorch Tensor ->`Numpy->torch.Tensor.numpy()`

In [89]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
array.dtype

dtype('float64')

In [91]:
torch.arange(1.0,8.0).dtype

torch.float32

In [92]:
#change the value of array, what will this do to `tensor`?
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
#change the tensor what happens to `numpy_tensor`?
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## pytorch reproducability(trying to take random out of random)

In shorts how a neural network learns:
`start with random numbers-> tensor opereration -> update random numbers to try and make them better reperesentation of the data -> again -> again -> again ....`

TO reduce the rendomness in neural network and pytorch comes the concept of random seed.
Essentially what the random seed does is "Flavour" the randomness

In [95]:
torch.rand(3,3)

tensor([[0.2723, 0.8848, 0.0054],
        [0.4607, 0.9246, 0.8779],
        [0.8206, 0.4034, 0.2834]])

In [96]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0171, 0.7028, 0.6034, 0.9970],
        [0.4856, 0.8606, 0.6042, 0.2251],
        [0.1295, 0.8940, 0.8245, 0.9486]])
tensor([[0.0066, 0.0009, 0.3752, 0.5666],
        [0.7313, 0.2878, 0.4468, 0.4773],
        [0.1669, 0.4970, 0.7826, 0.6592]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
# Let's make some random but reprodusable tensor

# set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## RUNNING TERNSOR AND PYTORCH OBJECTS ON THE GPU(and making the computation faster)

GPUs = Faster computaion on numbers,thanks to cuda + NVIDIA hardware + Pytorch working behind the scenes.

### Getting a GPU

1. Easiest Google colab- Free.
2. use a paid or use google colab Pro

In [100]:
#cheak for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [101]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [103]:
#count number of gpu
torch.cuda.device_count()

1

In [105]:
## Putting tensors and models on the GPU.
## the reasons we want out tensor on GPU because It is Faster

In [106]:
#Create a Tensor
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [107]:
## Move tensor on Gpu if available.

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Move tensor back to the cpu.

In [108]:
# If tensor on gpu can't transform them to Numpy.
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [109]:
# To fix the gpu tensor with Numpy issue, we can first set it on cpu.

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [110]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')