<a href="https://colab.research.google.com/github/beingTushar24/Pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


## Introduction to Tensors

## Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3 ,6 ,9],
                        [2 ,4 ,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor

why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those numbers to better represent the data.

In [45]:
## Random Tensor
## creating a random tensor of size 3X4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6994, 0.5911, 0.3531, 0.1529],
        [0.7157, 0.4955, 0.3151, 0.5802],
        [0.4190, 0.1356, 0.2970, 0.9673]])

In [21]:
random_tensor.ndim

3

In [40]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 4]), 2)

In [30]:
torch.rand(size=(3,3))

tensor([[0.7778, 0.3117, 0.6626],
        [0.5452, 0.2159, 0.1940],
        [0.7281, 0.8680, 0.8944]])

In [31]:
torch.rand(3,3)

tensor([[0.8272, 0.0586, 0.4010],
        [0.1115, 0.1046, 0.5680],
        [0.7092, 0.9459, 0.4143]])

### Zeros And Ones

In [42]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
zeros.shape

torch.Size([3, 4])

In [47]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
# Create a Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype

torch.float32

In [50]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like


In [55]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=0, end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Creating Tensor Like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])