<a href="https://colab.research.google.com/github/beingTushar24/Pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors

## Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3 ,6 ,9],
                        [2 ,4 ,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor

why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those numbers to better represent the data.

In [16]:
## Random Tensor
## creating a random tensor of size 3X4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5290, 0.4584, 0.4123, 0.5064],
        [0.1814, 0.7257, 0.2576, 0.1860],
        [0.8714, 0.9520, 0.3133, 0.1673]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 4]), 2)

In [19]:
torch.rand(size=(3,3))

tensor([[0.1573, 0.5093, 0.0758],
        [0.7537, 0.4670, 0.3739],
        [0.3755, 0.1558, 0.6499]])

In [20]:
torch.rand(3,3)

tensor([[0.9789, 0.5535, 0.2047],
        [0.2685, 0.1001, 0.7550],
        [0.8150, 0.9394, 0.3768]])

### Zeros And Ones

In [21]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros.shape

torch.Size([3, 4])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like


In [27]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=0, end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating Tensor Like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

*NOTE :* Tensors datatypes is one of the 3 big errors we'll run into pytorch & deep learning
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on the right device

In [35]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is a tensor(eg. float)
                               device=None,# whar device is your tensor on
                               requires_grad=False) # wheather or not to track gradeints with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9., 0.], dtype=torch.float16)

In [32]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.,  0.])

In [33]:
int_32_tensor = torch.tensor([3,4,9],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

### Getting information from tensor

1. Tensors not right Datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get a device from a tensor, can use tensor.device



In [38]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7204, 0.0225, 0.4044, 0.8595],
        [0.7339, 0.4226, 0.4024, 0.7651],
        [0.4102, 0.9939, 0.4354, 0.4443]])

In [39]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7204, 0.0225, 0.4044, 0.8595],
        [0.7339, 0.4226, 0.4024, 0.7651],
        [0.4102, 0.9939, 0.4354, 0.4443]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
