<a href="https://colab.research.google.com/github/beingTushar24/Pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors

## Creating tensors

In [49]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [50]:
scalar.ndim

0

In [51]:
# Get tensor back as python int
scalar.item()

7

In [52]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [53]:
vector.ndim

1

In [54]:
vector.shape

torch.Size([2])

In [55]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [56]:
MATRIX.ndim

2

In [57]:
MATRIX[1]

tensor([ 9, 10])

In [58]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3 ,6 ,9],
                        [2 ,4 ,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [60]:
TENSOR.ndim

3

In [61]:
TENSOR.shape

torch.Size([1, 3, 3])

In [62]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor

why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers then adjust those numbers to better represent the data.

In [63]:
## Random Tensor
## creating a random tensor of size 3X4
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5089, 0.5350, 0.2409, 0.5724],
        [0.0936, 0.0557, 0.8845, 0.5587],
        [0.3541, 0.8443, 0.1241, 0.5353]])

In [64]:
random_tensor.ndim

2

In [65]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 4]), 2)

In [66]:
torch.rand(size=(3,3))

tensor([[0.8731, 0.1824, 0.8573],
        [0.6769, 0.3614, 0.7195],
        [0.4058, 0.4701, 0.3887]])

In [67]:
torch.rand(3,3)

tensor([[0.6330, 0.2469, 0.9488],
        [0.6256, 0.3827, 0.1834],
        [0.6417, 0.7530, 0.8444]])

### Zeros And Ones

In [68]:
## Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
zeros.shape

torch.Size([3, 4])

In [70]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
# Create a Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
ones.dtype

torch.float32

In [73]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like


In [74]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten=torch.arange(start=0, end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
# Creating Tensor Like
one_to_ten_like = torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

*NOTE :* Tensors datatypes is one of the 3 big errors we'll run into pytorch & deep learning
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on the right device

In [76]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is a tensor(eg. float)
                               device=None,# whar device is your tensor on
                               requires_grad=False) # wheather or not to track gradeints with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [77]:
float_32_tensor.dtype

torch.float32

In [78]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [79]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [80]:
int_32_tensor = torch.tensor([3,4,9],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [81]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 81.])

### Getting information from tensor

1. Tensors not right Datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get a device from a tensor, can use tensor.device



In [82]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9452, 0.3091, 0.9546, 0.5212],
        [0.2825, 0.2222, 0.5546, 0.1928],
        [0.5718, 0.0825, 0.3517, 0.1705]])

In [83]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9452, 0.3091, 0.9546, 0.5212],
        [0.2825, 0.2222, 0.5546, 0.1928],
        [0.5718, 0.0825, 0.3517, 0.1705]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensor (tensor opereation)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [84]:
# Create a Tensor and add 10 to it

tensor = torch.tensor([1,2,3,4])
tensor +10

tensor([11, 12, 13, 14])

In [85]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30, 40])

In [86]:
# Substract -10

tensor - 10

tensor([-9, -8, -7, -6])

In [87]:
# Try out pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30, 40])

## Matrix Multiplication

Two main ways of performing Multiplication in nural network and deep learning

1.Element-wise Multiplication
2.Matrix multiplication(dot product)


In [88]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
Equals: tensor([ 1,  4,  9, 16])


In [89]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(30)

In [90]:
tensor

tensor([1, 2, 3, 4])

In [91]:
%%time
value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(30)
CPU times: user 1.5 ms, sys: 62 µs, total: 1.56 ms
Wall time: 1.45 ms


In [92]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 587 µs, sys: 0 ns, total: 587 µs
Wall time: 469 µs


tensor(30)

## one of the most common error in deep learning : shape error

In [93]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [95]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate tensor using a **transpose** switches the axis or dimensions of a given tensor.

In [96]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [97]:
## The matrix Multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


## finding the min, max, mean , sum ,etc(Tensor aggregation)

In [98]:
# create a tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [99]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [101]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [102]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [103]:
# find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [104]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [105]:
## find the position in the tensor that has the minimum value with argmin() -> returns index place of the minimum element in the tensor
x.argmin()


tensor(0)

In [106]:
x[0]

tensor(1)

In [107]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [108]:
x[9]

tensor(91)

## Reshaping stacking , squeezing , and unsquessing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory
* stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* seueeze - removes all `1` dimensional from a tensor
* Unsqueeze - add a `1` dimensional to a target tensor
* Permute - return a few input with dimensional pemuted (swapped) in a certain way

In [109]:
# let's create a tensor
x =  torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [110]:
# Add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [111]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
# changing z changes z (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [113]:
# stacking tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [118]:
# torch squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_squeeze
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [122]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimenion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [123]:
# torch.permute() - rearranges the dimension of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3)) #[height, width, colour_channel]

# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [124]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

In [115]:
x_reshaped.shape

torch.Size([1, 9])

In [116]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [117]:
x_reshaped.squeeze().shape

torch.Size([9])